[ln]
ln_backend = "fakewallet"
unit = "msat"
min_mint = 1000
max_mint = 500000000
min_melt = 1000
max_melt = 500000000

[[mint_info.ctf_registration_fees]]
unit = "msat"
registration_fee_base = 1000
registration_fee_per_keyset = 1000
